/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-24 05:20:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/all_component/allCss.jsp", Long.valueOf(1658371373258L));
    _jspx_dependants.put("/all_component/navbar.jsp", Long.valueOf(1658573728048L));
    _jspx_dependants.put("/all_component/footer.jsp", Long.valueOf(1658425238411L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Ebook: Index</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"all_component/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".back-img {\r\n");
      out.write("	background: url(\"img/book.jpg\");\r\n");
      out.write("	height: 60vh;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".crd-ho:hover {\r\n");
      out.write("	background-color: #ebecf0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #D3D3D3\">\r\n");
      out.write("	");
      out.write("<link rel=\"stylesheet\" href=\"all_component/style.css\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\" style=\"height: 10px; background-color:#303f9f\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid p-3 bg-light\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-3 text-success\">\r\n");
      out.write("<h3><i class=\"fa fa-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("E-books</h3>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-6\">\r\n");
      out.write(" <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-3\">\r\n");
      out.write("<a href=\"login.jsp\" class=\"btn btn-success\"><i class=\"fa-solid fa-right-to-bracket\"></i> Login</a>\r\n");
      out.write("<a href=\"register.jsp\" class=\"btn btn-primary text-white\"><i class=\"fa-solid fa-address-card\"></i> Register</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-custom\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\"> <i class=\"fa fa-home\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\"><i class=\"fas fa-book-open\" ></i> New Book</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\"><i class=\"fas fa-book-open\"></i> Recent Book</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\"><i class=\"fas fa-book-open\"></i> Old Book</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">   \r\n");
      out.write("      <button class=\"btn btn-btn-light my-2 my-sm-0\" type=\"submit\"><i class=\"fas fa-user-cog\"></i>Setting</button>\r\n");
      out.write("      <button class=\"btn btn-btn-light my-2 my-sm-0 ml-1\" type=\"submit\"><i class=\"fa fa-phone-square\" aria-hidden=\"true\"></i>Contact us</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid back-img\">\r\n");
      out.write("		<h2 style=\"text-align: center; color: white;\">E-book Management\r\n");
      out.write("			System</h2>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<!-- 	RECENT BOOK -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center\">Recent Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3\">  \r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"><i class=\"fa-solid fa-cart-plus\"></i>Add to cart</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"><i class=\"fa-solid fa-cart-plus\"></i>Add to cart</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"><i class=\"fa-solid fa-cart-plus\"></i>Add to cart</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"><i class=\"fa-solid fa-cart-plus\"></i>Add to cart</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("		<a herf=\"\" class=\"btn btn-danger btn-sm text-white\">View All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- 	RECENT BOOK END -->\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("<!-- 	NEW BOOK -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center\">New Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3\">  \r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"><i class=\"fa-solid fa-cart-plus\"></i>Add to cart</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"><i class=\"fa-solid fa-cart-plus\"></i>Add to cart</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"><i class=\"fa-solid fa-cart-plus\"></i>Add to cart</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"><i class=\"fa-solid fa-cart-plus\"></i>Add to cart</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("		<a herf=\"\" class=\"btn btn-danger btn-sm text-white\">View All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("<!-- 	NEW BOOK END -->\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!-- OLD BOOK -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center\">Old Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3\">  \r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							 <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-5\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							 <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-5\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							 <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-5\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"book/python.jpeg\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("						<p>The Python Book</p>\r\n");
      out.write("						<p>Cairon Berry</p>\r\n");
      out.write("						<p>Category: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("						 <a href=\"\" class=\"btn btn-success btn-sm ml-5\">View Detail</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-success btn-sm ml-1\">370</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("		<a herf=\"\" class=\"btn btn-danger btn-sm text-white\">View All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<!-- OLD BOOK END -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid text-center text-white p-3 mt-2\" style=\"background-color: #303f9f;\">\r\n");
      out.write("<h5>Designed and Developed by VEGA team</h5>\r\n");
      out.write("</div>");
      out.write(">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
